### ISSUE TITLE
Dropbox recordings don't sync to Windows folder, ":" prevents sync

### ISSUE THREAD

**Issue by MagicFab** [jitsi/jibri#294]
When recording to Dropbox, it seems the file contains a ":" separator for time.

Several posts in the forums complain about not finding their recordings when in fact they are saved at Dropbox.com but haven't sync'ed to their Windows folder as expected. 

As a workaround, renaming the file at dropbox.com will make Dropbox sync it to the Windows system.

A possible fix would be to use another file name convention and remove the ":" as a time separator.

**Comment by bbaldino** [comment]
The timestamp for the file has never used colons; it uses dashes, like so: `2020-05-20-10-57-15`.  We don't use any colons explicitly in the filename, did you have a colon in your meeting name maybe?

**Comment by MagicFab** [comment]
I just tested this on https://meet.jit.si and a colon is used in the timestamp.

![image](https://user-images.githubusercontent.com/317514/82482677-32283a80-9aa5-11ea-8979-a22c74af8dae.png)

**Comment by bbaldino** [comment]
Ah, this must be in the dropbox uploader.  @hristoterezov, it looks like colons in the filename are causing issues on Windows.

**Comment by aaronkvanmeerten** [comment]
Yes this is an issue in https://github.com/jitsi/jitsi-upload-integrations so we should move the issue there.  It's specifically this part: 
            MTIME=$(stat -c %Y "$i")
            FDATE=$(date --date="@$MTIME" '+%F %R')

**Comment by aaronkvanmeerten** [comment]
This issue was raised for the same in jitsi-upload-integrations: https://github.com/jitsi/jitsi-upload-integrations/issues/13

**Comment by aaronkvanmeerten** [comment]
I now have a PR open to resolve this issue: https://github.com/jitsi/jitsi-upload-integrations/pull/14

**Comment by aaronkvanmeerten** [comment]
This is now fixed in the latest debian build for the upload integrations: jitsi-upload-integrations_0.14.14-1_all.deb

**Comment by MagicFab** [comment]
I am still getting v0.13.13-1 via regular updates. Can someone confirm when this should be available ? Has https://meet.jit.si gotten this fix ?

**Comment by MagicFab** [comment]
For the sake of completeness, I've just tested this again and the recording now don't use a semi-colon.

The file name used looks like "jitsiroomname on 2022-04-29 14-45.mp4" under :
/Dropbox/Apps/Jitsi Meet/Recordings
