### ISSUE TITLE
ERROR: Failed audio check, no audio level detected: 1

### ISSUE THREAD

**Issue by subsub** [jitsi/jibri#55]
I have passed the selenium test, ffmpeg test, and youtube stream test, all done and succeed. I even check audio and (I suppose) it succeed. This is the output of check audio from /tmp/jibri-check_audio.log:
```
Recording raw data '/tmp/jibri-audio_check.wav' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Hardware PCM card 0 'Loopback' device 1 subdevice 0
Its setup is:
  stream       : CAPTURE
  access       : RW_INTERLEAVED
  format       : S16_LE
  subformat    : STD
  channels     : 2
  rate         : 44100
  exact rate   : 44100 (44100/1)
  msbits       : 16
  buffer_size  : 22052
  period_size  : 5513
  period_time  : 125011
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 5513
  period_event : 0
  start_threshold  : 1
  stop_threshold   : 22052
  silence_threshold: 0
  silence_size : 0
  boundary     : 6207086186423386112
  appl_ptr     : 0
  hw_ptr       : 0
```

But everytime I start live stream an error occurs telling that it failed audio check. Here's the log:
```
-- Logs begin at Kam 2017-11-02 11:54:21 WIB, end at Kam 2017-11-02 13:48:07 WIB. --
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,013 INFO     Creating a client for hostname: my.domain.com with options: {'jidserver_prefix': 'auth.', 'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'boshdomain': 'recorder.my.domain.com', 'jid_username': 'jibri', 'usage_timeout': 0, 'selenium_xmpp_password': 'mypassword', 'roomname': 'TheBrewery', 'selenium_xmpp_prefix': 'recorder.', 'password': 'mypassword', 'roompass': '', 'brewery_prefix': 'conference.', 'mucserver_prefix': 'conference.', 'boshdomain_prefix': 'recorder.', 'nick': 'jibri-41832950736615837', 'xmpp_domain': 'my.domain.com', 'selenium_xmpp_username': 'recorder', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%', 'recording_directory': './recordings', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com'}
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,017 INFO     jibri_watcher starting up...
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,115 INFO      * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
Nov 02 13:22:35 jibri app.py[3473]: 2017-11-02 13:22:35,152 WARNING  jid property deprecated. Use boundjid.bare
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,562 INFO     Negotiating TLS
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,563 INFO     Using SSL version: TLS 1.0
Nov 02 13:22:36 jibri app.py[3473]: 2017-11-02 13:22:36,707 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,769 INFO     JID set to: jibri@auth.my.domain.com/8a985663-a5a4-4aab-a881-a73b22bad4f6
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,831 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,832 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>, connecting to room TheBrewery@conference.my.domain.com as jibri-41832950736615837
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,889 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="idle" /></presence>
Nov 02 13:22:37 jibri app.py[3473]: 2017-11-02 13:22:37,893 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,208 INFO     on_jibri_iq: <iq to="jibri@auth.my.domain.com/8a985663-a5a4-4aab-a881-a73b22bad4f6" id="amlicmlAYXV0aC50c3QuZWRwbHVzLmJpei84YTk4NTY2My1hNWE0LTRhYWItYTg4MS1hNzNiMjJiYWQ0ZjYAU1dPNXctOTQ3ODAAfGj5zxYb8haA9jrz8CkCzw==" from="thebrewery@conference.my.domain.com/focus" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" recording_mode="stream" streamid="youtube-stream-key" room="test@conference.my.domain.com" action="start" /></iq>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,213 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="busy" /></presence>
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,214 INFO     Client options for host: {'jidserver_prefix': 'auth.', 'selenium_xmpp_login': 'recorder@recorder.my.domain.com', 'boshdomain': 'recorder.my.domain.com', 'jid_username': 'jibri', 'usage_timeout': 0, 'selenium_xmpp_password': 'mypassword', 'roomname': 'TheBrewery', 'selenium_xmpp_prefix': 'recorder.', 'password': 'mypassword', 'roompass': '', 'brewery_prefix': 'conference.', 'mucserver_prefix': 'conference.', 'boshdomain_prefix': 'recorder.', 'nick': 'jibri-41832950736615837', 'xmpp_domain': 'my.domain.com', 'selenium_xmpp_username': 'recorder', 'url': 'https://my.domain.com/%SUBDOMAIN%%ROOM%', 'recording_directory': './recordings', 'room': 'TheBrewery@conference.my.domain.com', 'jid': 'jibri@auth.my.domain.com'}
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp login from client options: recorder@recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp password from client options
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting boshdomain from client options recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,215 INFO     Setting xmpp_domain from client options my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,216 INFO     Setting mucserver_prefix from client options conference.
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,216 INFO     Setting recording_directory from client options ./recordings
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Start recording callback
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     update_jibri_status
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     looping through queue for host my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Starting jibri
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,226 INFO     Starting selenium attempt 1/3 pjsua_flag:False
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,227 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:23:51 jibri app.py[3473]: 2017-11-02 13:23:51,227 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,516 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,520 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,525 INFO     start_jibri_selenium returned retcode=3 during attempt 1/3
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,525 INFO     Starting selenium attempt 2/3 pjsua_flag:False
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,526 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:24:09 jibri app.py[3473]: 2017-11-02 13:24:09,526 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,475 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,480 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     start_jibri_selenium returned retcode=3 during attempt 2/3
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     Starting selenium attempt 3/3 pjsua_flag:False
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,481 INFO     overriding config.hosts.domain with boshdomain: recorder.my.domain.com
Nov 02 13:24:16 jibri app.py[3473]: 2017-11-02 13:24:16,484 INFO     starting jibri selenium, url=https://my.domain.com/test#config.iAmRecorder=true&config.externalConnectUrl=null&config.hosts.domain="recorder.my.domain.com", google_account=None, xmpp_login=recorder@recorder.my.domain.com
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,430 WARNING  ERROR: failed audio check, no audio levels detected: 1
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,436 WARNING  jibri detected audio issues during startup, bailing out.
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     start_jibri_selenium returned retcode=3 during attempt 3/3
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     start_jibri_selenium returned retcode=3
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,441 INFO     jibri_stop_callback run with status startup_selenium_error
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,442 INFO     queueing error error|startup_selenium_error for host my.domain.com
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,442 INFO     queueing job for jibri_watcher
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,443 INFO     jibri_watcher received job, now watching ffmpeg and selenium with a timeout of 0.
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,443 INFO     jibri_watcher finished loop...
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,444 INFO     jibri_watcher starting up...
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,956 INFO     got msg from main: error|startup_selenium_error
Nov 02 13:24:24 jibri app.py[3473]: 2017-11-02 13:24:24,963 INFO     sending status update: <iq to="thebrewery@conference.my.domain.com/focus" id="2d179cbd-deeb-4b2d-b052-28c1099f9ef8-7" type="set"><jibri xmlns="http://jitsi.org/protocol/jibri" status="failed"><error xmlns="jabber:client" code="504" type="wait"><remote-server-timeout xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /><text xmlns="urn:ietf:params:xml:ns:xmpp-stanzas">Startup error: Selenium error</text><retry xmlns="http://jitsi.org/protocol/jibri" /></error></jibri></iq>
Nov 02 13:24:27 jibri app.py[3473]: 2017-11-02 13:24:27,646 ERROR    Exception in callback jibri_start_callback(<jibrixmppcli...x7f3b957afbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310
Nov 02 13:24:27 jibri app.py[3473]: handle: <Handle jibri_start_callback(<jibrixmppcli...x7f3b957afbe0>, '', 'stream', 'youtube-stream-key', '', '', ...) at /home/jibri/jibri-xmpp-client/app.py:310>
Nov 02 13:24:27 jibri app.py[3473]: Traceback (most recent call last):
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
Nov 02 13:24:27 jibri app.py[3473]:     self._callback(*self._args)
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 521, in jibri_start_callback
Nov 02 13:24:27 jibri app.py[3473]:     jibri_stop_callback('startup_selenium_error')
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 794, in jibri_stop_callback
Nov 02 13:24:27 jibri app.py[3473]:     finalize_recording()
Nov 02 13:24:27 jibri app.py[3473]:   File "/home/jibri/jibri-xmpp-client/app.py", line 203, in finalize_recording
Nov 02 13:24:27 jibri app.py[3473]:     call([finalize_recording_script,recording_directory])
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 557, in call
Nov 02 13:24:27 jibri app.py[3473]:     with Popen(*popenargs, **kwargs) as p:
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
Nov 02 13:24:27 jibri app.py[3473]:     restore_signals, start_new_session)
Nov 02 13:24:27 jibri app.py[3473]:   File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
Nov 02 13:24:27 jibri app.py[3473]:     raise child_exception_type(errno_num, err_msg)
Nov 02 13:24:27 jibri app.py[3473]: PermissionError: [Errno 13] Permission denied
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,867 ERROR    Socket Error #104: Connection reset by peer
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,868 WARNING  Failed to send b'</stream:stream>'
Nov 02 13:47:37 jibri app.py[3473]: 2017-11-02 13:47:37,869 INFO     Waiting for </stream:stream> from server
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,475 INFO     Negotiating TLS
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,476 INFO     Using SSL version: TLS 1.0
Nov 02 13:47:44 jibri app.py[3473]: 2017-11-02 13:47:44,836 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate COULD NOT BE VERIFIED.
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,349 INFO     JID set to: jibri@auth.my.domain.com/e7d2b396-627a-4a7c-88f3-3bebf2a08ea5
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,407 WARNING  Could not find pyasn1 and pyasn1_modules. SSL certificate expiration COULD NOT BE VERIFIED.
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,408 INFO     Starting up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>, connecting to room TheBrewery@conference.my.domain.com as jibri-41832950736615837
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,480 INFO     sending presence: <presence xml:lang="en" to="TheBrewery@conference.my.domain.com"><jibri-status xmlns="http://jitsi.org/protocol/jibri" status="idle" /></presence>
Nov 02 13:47:45 jibri app.py[3473]: 2017-11-02 13:47:45,482 INFO     Started up client <jibrixmppclient.JibriXMPPClient object at 0x7f3b957afbe0>
```

Please help, who ever have knowledge in this issue since. Thank you.

**Comment by damencho** [comment]
Can you check scripts/finalize_recording.sh, is it executable? 
Ups that is not executable in the source code repo, will fix that.

**Comment by damencho** [comment]
I just fixed it in the repo, you can simply pull latest version.

**Comment by subsub** [comment]
@damencho I pulled from latest version. But it didn't fix audio check issue.

**Comment by subsub** [comment]
@damencho eventually I got to fix it by changing the hardware to use `hw:1,0` in check_audio.sh. Now check audio success.

**Comment by damencho** [comment]
My fix was for PermissionError: [Errno 13] Permission denied
